server:
  port: 8821

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: pIAzKrQ4ssD1tAxvFxqipRmDeKqq2TGqWP8vt4Awj7lk6Z5YjpWUhGAVd3vMT0X8idkuMyktbsykUlcFnepnpA==
      url: jdbc:mysql://39.108.137.115:3306/test?serverTimezone=UTC&useSSL=false
      initial-size: 5
      max-active: 20  #最多可以连接20个数据库
      #      max-evictable-idle-time-millis: 40000
      max-open-prepared-statements: -1
      max-wait: -1   #表示无限制
      #      min-evictable-idle-time-millis: 300000
      min-idle: 5
      pool-prepared-statements: false
      time-between-eviction-runs-millis: 60000
      filter:
        config:
          enabled: true
      connection-properties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALl+uGnrTVpFFkm6oCZShN6OWynRzFM591wlS6t3Q7WxTuaMImp+pL37gSGbHNXRqk6AzGGQSm2ADAIuTo0ZacsCAwEAAQ==
      #      这两个参数很关键，是否配置了代理
      test-on-borrow: true
      test-while-idle: true
  redis:
    host: 39.108.137.115
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 0
        max-idle: 8

    port: 6379
    password: 123456

mybatis:
  check-config-location: false
  mapper-locations: classpath*:/mappers/*.xml
  type-aliases-package: com.github.spring.components.learning.transaction.pojo
  #  开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true


#配置代理接口全限定名即ioc中 beanDefinitionName
service:
  namespace: com.github.spring.components.learning.transaction.service
#配置依赖注入bean后缀
match:
  controller: Controller


logging:
  level:
    com.github.spring.components.transaction.dao: debug

#mybatis-plus:
#  mapper-locations: classpath*:/mappers/*.xml
#  type-aliases-package: com.sjl.spring.components.transaction.pojo

#自定义通用mapper 注册器包扫描路经
dao:
  scan:
    packages: com.github.spring.components.learning.transaction.dao
#    condition config
os:
  name: mac
#xxl-job 配置
xxl:
  job:
    #    accessToken: ''
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      #      address: ''
      appname: xxl-job-executor-sample
      ip: 127.0.0.1
      logpath: /Users/shijianlei/logs/applogs/xxl-job/jobhandler
      logretentiondays: 30
      port: 9999
#监控启用所有断点
management:
  endpoints:
    web:
      exposure:
        include: "*"

#sight
sight:
  base:
    url: http://127.0.0.1:9988/