server:
  port: 8849

nacos:
  config:
    server-addr: 127.0.0.1:8848
spring:
  application:
    name: spring-boot-nacos-sample

app:
  name: Wechat

http:
  url: http://127.0.0.1:9988

simple:
  thread:
    pool:
      corePoolSize: 4
      maxPoolSize: 8
      keepAliveTime: 2
      initialDelay: 2
      period: 2
      delay: 2
